### PR TITLE
Refactor: split bootstrap actions and allow custom

### PR DESCRIPTION
**Pull request by fpytloun**
Another huge refactor for better maintainability and customizations.
Also enhance cleanup a little bit by killing leftover processes and removing resolv.conf

### CODE REVIEW

**Comment by fpytloun** [comment]
Example use: https://github.com/tcpcloud/rpi2-gen-image

**Comment by drtyhlpr** [comment]
wow nice patch - I like the split up but I hope I will not get to complicated if you read the script for the frist time, I ll maybe just add a more details comment in the script. give me some time to test (and check the merge conflicts) - I was currenly working on a patch for put 6, 7 more "files" out of the scipt (apt, xorg, u-boot, networking(!)) -simply using default values inside the files and sed replace /default/ - after install 644, if needed.

thanks for your work

**Comment by drtyhlpr** [comment]
if many uses require the "kubernetes, docker, contrail vrouter", these features must be added as optional parameters to not give users who don't need them something they don't want :) ... hm smells like lot of work - it would also be ok to remove them from this PR and add them as sperate PR(s) thx

**Comment by fpytloun** [comment]
Sorry, I pushed image for kubernetes accidentaly, it shouldn't be part of this pull request, I will fix it :-)
I think it's not more complicated to read, maybe easier.

I already checked how to refactor to split more stuff into files (basically a templates) and it can be done using `envsubst` - and simply use bash variables inside config files.

```envsubst < source.conf > destination.conf```

It would be good to have this pull request merged as soon as other things are commited, otherwise I will burn in merge conflicts fixing hell.

**Comment by drtyhlpr** [comment]
yes, I am busy today .... maybe time for some background compilation tasks :) - but I will definitely merge this PR before anything else but I will also need to add a small section to the README.md about:

- ./files (because the dir structure will not be the same as the dst in chroot - with one liner)
- ./bootstrap.d (maybe explaining 10-,11-,12-,13 .. 20-.. with a simple one liner)

**Comment by drtyhlpr** [comment]
s/envsubst hehe yeah and there is this >> awk << cmdline for that you can use. hm I checked the files and I think 2-3 are static anyway, and some only have 1 or 2 replacement strings (sources.list, server, release, and uboot cmdline (replace ^ hehe) so 2x sed or even 2x tr ... the further split down to files patch will be applied after this PR so no worries!

**Comment by drtyhlpr** [comment]
This branch has no conflicts with the base branch - YES  .... damn I have to go ttyl

**Comment by fpytloun** [comment]
Yes, I fixed conflicts and enhanced kernel build/install a little bit :-)

**Comment by drtyhlpr** [comment]
merged :) and applied mini fix

**Comment by fpytloun** [comment]
thanks :-)

**Pull request closed without merging**
