### PR TITLE
Option to disable rsyslog and improvements (including security fix)

### PR DESCRIPTION
**Pull request by fpytloun**
- Introduce chroot_exec function
- Allow choosing custom kernel
- Install raspberrypi-bootloader-nokernel package instead of getting firmware
  with wget
- Option to disable rsyslog and use only journald
- [SECURITY] ensure ssh host keys are generated on first boot
- Expand root partition and FS on first boot (origin from https://github.com/drtyhlpr/rpi2-gen-image/pull/17)
- Refactor: split static files from main file

### CODE REVIEW

**Comment by drtyhlpr** [comment]
very very nice patch - give me some time to test I am sure to merge this stuff soon. ty

about the SSH key regen (and some manual rm of sshd stuff) - I am not sure if this is anyhow related to the 'screen' problem -> #10 - i tought about a dirty & final "sudo apt-get -y purge openssh-server && sudo apt-get -y install openssh-server" at the end of the script.

I did not have time to test the last month ... but I still wanna figure out why #10 happens.

**Comment by fpytloun** [comment]
I am not sure what's causing #10 (didn't hit that issue yet) but will try to check later.
Anyway both key regeneration and root fs expand are working fine (final image is available here: http://apt.tcpcloud.eu/images/debian-8-armhf-rpi2-1457098255.img.bz2) at least what I have tested.

I am going to refactor the code a little bit more when this is merged to make customizations to the image easier (more splitting).

A little OT from this merge request:
- who is maintaining packages at collabora? They seems to be a little bit older.
- + is there any chance to get these packages/patches to Debian directly so that 3rd party repo will not be needed?

I am also hitting weird issue with FS corruption and I think it's caused by this old firmware + kernel :-/

**Comment by drtyhlpr** [comment]
you are correct this collabora packages are heavily outdated. I am planing to add a custom kernel compile (in general https://www.raspberrypi.org/documentation/linux/kernel/building.md) with optional initramfs. not sure about the rpi default bootloader (I think I experienced some problems with the - at this time - current boot/kernel combination - this is why I am ref cd355a9dd4f1f4de2e79b0c8e102840885cdf1de of the github - but this was like some months ago).

another options would be this mixed mode with rasbian (that also may cause problems) not sure about the exact risks -> #26.

I am not related to debian - and I dont have an idea about their repro plans. I think most people use raspbian anyway.

**Comment by fpytloun** [comment]
Well, my motivation on using this project is more clean distribution than Raspbian or any other fork.
So I would more appreciate some community efford on doing things as "cleanest and debianist" as possible - maintain repository with RPI specific packages or better try to push patches to Debian directly.
Some of the packages can be taken from raspbian without much modifications (eg. raspbian-firmware-nokernel, flash-tools), some of them not (eg. kernel which is currently bundled together with firmware).

**Comment by daniell1** [comment]
The collabora kernel is maintained by Sjoerd Simons: http://sjoerd.luon.net/posts/2015/02/debian-jessie-on-rpi2/. Because his kernel is outdated, I forked this script to use Raspbian kernel and boot binaries: https://github.com/daniell1/rpi2-gen-image. Denis (from the followers list) told me that there might be official Debian support for the RPi2 when there is support in vanilla kernel. Currently you either have to use Sjoerd's image or your script if you want to get packages directly from Debian including their security repo (assuming you don't want to build everything on your own again). Btw: Debian wiki's RPi2 page is mentioning your script: https://wiki.debian.org/RaspberryPi2.

**Comment by drtyhlpr** [comment]
the merging works nice but I receive an warning and and stops hard on adduser error.

warning:
> + echo deb https://repositories.collabora.co.uk/debian jessie rpi2
> + chroot_exec apt-get -qq -y update
> + LANG=C LC_ALL=C chroot ./images/jessie/build/chroot apt-get -qq -y update
> W: GPG error: https://repositories.collabora.co.uk jessie InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C8355DB5B5FBB289

error:
> + chroot_exec adduser --gecos "Raspberry PI user" --add_extra_groups --disabled-password pi
> + LANG=C LC_ALL=C chroot ./images/jessie/build/chroot adduser --gecos "Raspberry PI user" --add_extra_groups --disabled-password pi
> adduser: Only one or two names allowed.

ps. I can not find the key on a keyserver (otherwise this would be easy to fix)

need to investigate.

**Comment by fpytloun** [comment]
Warning is ok, because collabora archive keyring is installed after forced update
```
echo "deb https://repositories.collabora.co.uk/debian ${RELEASE} rpi2" >$R/etc/apt/sources.list
chroot_exec apt-get -qq -y update
chroot_exec apt-get -qq -y --force-yes install collabora-obs-archive-keyring
```

Error is only about escaping (should be fixed now).

**Comment by drtyhlpr** [comment]
great - I tried some stuff that did not work.

**Comment by drtyhlpr** [comment]
hm shit ... I tried many escaping variants and feel stupid but it still does not work - no matter if

> \" \\\\" or "\\\\"

still the same error.

I need to continue other work today and don't have mutch time. maybe you have an idea for a fix?

**Comment by fpytloun** [comment]
Ok, fixed now (and tested).
I will have to rebase due to APT_INCLUDES merge.

**Comment by drtyhlpr** [comment]
hmmm... argh it still does not work for me. and don't get me wrong I am very happy with this great PR. well after 10other failed tries I will now simply rename the damn user - not a professional but a working solution (loosing lifetime on escapes argh:)

**Comment by fpytloun** [comment]
Weird, adduser passed fine for me O.o

**Pull request merged**
